### ISSUE TITLE
Postgresql 12 compatibility

### ISSUE THREAD

**Issue by e1himself** [rock-symphony/propel-orm#14]
There's an error thrown when you try to read database schema from Postgresql 12 database.

Here:
https://github.com/rock-symphony/propel-orm/blob/ee7af27963a1d367b8c11c2a1312f4150f6b6119/generator/lib/reverse/pgsql/PgsqlSchemaParser.php#L173-L194

That's because `def.adsrc` is no longer there. Instead it should use `pg_get_expr(def.adbin, def.adrelid) as adsrc`.

**Comment by digitalbase** [comment]
Isn't this a propel bug ?

**Comment by e1himself** [comment]
@digitalbase yes, this is a Propel bug and this is the Propel ORM repository :)
